# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# your properties
# https://www.curseforge.com/minecraft/mc-mods/flib
mod_id=flib
curse_id=661261
mod_version=0.0.13

mc_version=1.20.1
neo_version=47.1.105


mod_name=flib
mod_group_id=com.lothrazar.flib


mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=Future Library.  Empowers many forge mods. 

mapping_version=1.20.1
mapping_channel=official



#jei_version=15.0.0.23
#curios_version=5.7.2
