
mod_version=0.2.9

mod_id=flib
mod_license=MIT
mod_authors=Lothrazar
mod_description=mod
mod_name=flib
mod_group_id=com.lothrazar.library
curse_slug=flib
curse_id=661261
modrinth_id=flib


#flib_version=0.1.0
#flib_file=8006351


